<?php
/**
 * Baz view template
 *
 * @var $block \Foo\Bar\Block\Baz
 */
?>
	<div class="jumbotron-wrapper">
	<div id="layerslider" class="fullwidth" style="width:1440px;height:500px;">
		<div class="ls-slide" data-ls="bgsize:cover;bgposition:50% 50%;overflow:true;kenburnsscale:1.2;duration: 7000;bgcolor:#fff;">
			<img width="1440" height="500" src="<?php echo $this->getViewFileUrl('Emmesaurus_Layerslider::images/filterqueenslide.jpg'); ?>" class="ls-bg" alt="landing-intro-bg">
			</div>
	<div class="ls-slide" data-ls="bgsize:cover;bgposition:50% 50%;overflow:true;kenburnsscale:1.2;duration: 7000;">
			<img width="1440" height="500" src="<?php echo $this->getViewFileUrl('Emmesaurus_Layerslider::images/mielec3comfortparquetslide.jpg'); ?>" class="ls-bg" alt="landing-intro-bg">
			<img width="1440" height="500" src="<?php echo $this->getViewFileUrl('Emmesaurus_Layerslider::images/mielec2comfortparquetslidetext.png'); ?>" class="ls-l" alt="Nellies Logo" style="top:50%;left:50%;" data-ls="offsetxin:200;offsetyin:-100;rotatein:20;offsetxout:-80;durationout:400;position:fixed;">
			</div>
			<div class="ls-slide" data-ls="bgsize:cover;bgposition:50% 50%;overflow:true;kenburnsscale:1.2;duration: 7000;">
			<img width="1440" height="500" src="<?php echo $this->getViewFileUrl('Emmesaurus_Layerslider::images/beam60thsaleslidebg.jpg'); ?>" class="ls-bg" alt="landing-intro-bg">
			<img width="1440" height="500" src="<?php echo $this->getViewFileUrl('Emmesaurus_Layerslider::images/beam60thsaletext.png'); ?>" class="ls-l" alt="Nellies Logo" style="top:50%;left:50%;" data-ls="offsetxin:200;offsetyin:-100;rotatein:20;offsetxout:-80;durationout:400;position:fixed;">
			</div>
						<div class="ls-slide" data-ls="bgsize:auto;bgposition:0px 0px;overflow:true;kenburnsscale:1.2;duration: 7000;bgcolor:#dcdbdf;">
			<img width="987" height="500" src="<?php echo $this->getViewFileUrl('Emmesaurus_Layerslider::images/miele10yearslidebg.jpg'); ?>" class="ls-bg" alt="landing-intro-bg">
			<img width="453" height="500" src="<?php echo $this->getViewFileUrl('Emmesaurus_Layerslider::images/miele10yearslidetext.png'); ?>" class="ls-l" alt="Nellies Logo" style="top:50%;left:100%;" data-ls="offsetxin:200;offsetyin:-100;rotatein:20;offsetxout:-80;durationout:400;position:fixed;">
			</div>
				<div class="ls-slide" data-ls="bgsize:auto;bgposition:50% 50%;overflow:true;kenburnsscale:1.2;duration: 7000;bgcolor:#fff;">
			<img width="1280" height="375" src="<?php echo $this->getViewFileUrl('Emmesaurus_Layerslider::images/retraflexslide.jpg'); ?>" class="ls-bg" alt="landing-intro-bg">
			</div>
		</div>
</div>
		<!-- LayerSlider end -->
<script type="text/javascript">
    require(['jquery','greensock','layerslidertransitions','layersliderjquery'],function($, jQuery){
        $(window).load(function() {
        $("#layerslider").layerSlider({
	        type: 'fullwidth',
	        fitScreenWidth: true,
			height: 500,
			maxRatio: 1,
			optimizeForMobile: true,
			skinsPath: '<?php echo $this->getViewFileUrl('Emmesaurus_Layerslider::images/'); ?>/skins/'
		});

 	});

});
</script>
