<li><a href="tel:+18664358675"><span class="icon-nexus-phone"><span>1-866-435-8675</span></span></a></li>
<li><span class="icon-nexus-map"><span translate="no" typeof="schema:PostalAddress">
  <span property="schema:streetAddress">15206 Stony Plain Rd NW</span> <span property="schema:addressLocality">Edmonton</span>, <abbr title="Alberta" property="schema:addressRegion">AB</abbr> <span property="schema:postalCode">T5P 3Y5</span> <abbr property="schema:addressCountry">CA</abbr>
</span></span></li>