<div class="footer-social-wrap">
	<div class="block-title"><?php echo $block->getTitle(); ?></div>
<ul>
	<li><a href="https://www.facebook.com/Vacuum-Central-296305967241660/"><span class="icon-nexus-facebook"><span>Vacuum Central on Facebook</span></span></span></span></a>
	</li>
	<li><a href="https://twitter.com/vacuumcentral"><span class="icon-nexus-twitter"><span>@vacuumcentral on Twitter</span></span></a></li>
	</li>
	<li><a href="https://plus.google.com/+VacuumCentralEdmonton"><span class="icon-nexus-googleplus"><span>Vacuum Central on Google Plus</span></span></a>
	</li>
	<li><a href="http://www.yelp.ca/biz/vacuum-central-edmonton-2"><span class="icon-nexus-yelp"><span>Vacuum Central on Yelp</span></span></a>
	</li>
	<li><a href="https://www.pinterest.com/vacuumcentral/"><span class="icon-nexus-pinterest"><span>Vacuum Central on Pinterest</span></span></a>
	</li>
	<li><a href="https://www.google.ca/search?q=Vacuum+Central+edmonton"><span class="icon-nexus-googlereview"><span>Vacuum Central on Google</span></span></a>
	</li>
</ul>
</div>