<ul class="credibility-blocks">
<li><img src="<?php echo $this->getViewFileUrl('Emmesaurus_Theme::images/CCA_20172017.png')?>" alt="Consumer Choice Awards" /></li>
<li>
<table style="width: 135px; margin-left: auto; margin-right: auto; margin-top: 25px;" title="Click to Verify - This site chose GeoTrust SSL for secure e-commerce and confidential communications." border="0" cellspacing="0" cellpadding="2">
<tbody>
<tr>
<td align="center" valign="top" width="135">
<script src="https://seal.geotrust.com/getgeotrustsslseal?host_name=discountvacuums.com&amp;size=S&amp;lang=en" type="text/javascript" xml="space"></script>
<br /> <a style="color: #000000; text-decoration: none; font: bold 7px verdana,sans-serif; letter-spacing: .5px; text-align: center; margin: 0px; padding: 0px;" href="http://www.geotrust.com/ssl/" target="_blank"></a></td>
</tr>
</tbody>
</table>
</li>
<li><a title="Click for the Business Review of Vacuum Central, a Vacuum Cleaners - Service &amp; Repair in Edmonton AB" href="//www.bbb.org/edmonton/business-reviews/vacuum-cleaners-service-and-repair/vacuum-central-in-edmonton-ab-103204#sealclick"><img style="border: 0px; margin-top: 20px; margin-bottom: 0px;" src="//seal-edmonton.bbb.org/seals/blue-seal-63-134-whitetxt-vacuumcentral-103204.png" alt="Click for the BBB Business Review of this Vacuum Cleaners - Service &amp; Repair in Edmonton AB" data-pin-nopin="true" /></a></li>
</ul>